apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    droneci/repo-url: https://drone.nogada.kubepia.net/api/repos/${{ parameters.owner }}/${{ values.name }}
  name: "${{ values.name }}"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
